INSERT INTO users (username, email, admin, password, description, city, province, country, image)
VALUES
  ('john_doe', 'john.doe@example.com', false, 'password', 'John Doe is a software developer with a passion for creating innovative solutions. He enjoys coding in various programming languages and constantly seeks new challenges in the tech world.', 'TechCity', 'TechProvince', 'TechLand', 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704906798/LHL%20Final%20Project/Users/user-1.jpg'),

  ('emma_smith', 'emma.smith@example.com', true, 'password', 'Emma Smith works for a charity organization, dedicated to making a positive impact on society. She is passionate about social causes and works tirelessly to bring about positive change in the community.', 'Hopeville', 'Helpshire', 'Helpland', 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704906816/LHL%20Final%20Project/Users/user-2.jpg'),

  ('alex_wong', 'alex.wong@example.com', false, 'password', 'Alex Wong is a skilled software developer who loves building scalable and efficient software systems. He enjoys tackling complex problems and is always looking for opportunities to learn and grow in the ever-evolving field of technology.', 'Codeburg', 'DevState', 'Techtopia', 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704906818/LHL%20Final%20Project/Users/user-3.jpg'),

  ('sarah_miller', 'sarah.miller@example.com', true, 'password', 'Sarah Miller is committed to making a difference in the world through her work at a charity organization. She believes in the power of collective action and works towards creating a better future for those in need.', 'Heartsville', 'Aidland', 'Helpsville', 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704990003/LHL%20Final%20Project/Users/user-4.jpg'),

  ('kevin_perez', 'kevin.perez@example.com', false, 'password', 'Kevin Perez is a software developer fascinated by the intersection of technology and creativity. He enjoys building user-friendly applications that provide meaningful solutions to real-world problems.', 'Innovatown', 'TechState', 'Codeania', 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704990005/LHL%20Final%20Project/Users/user-5.jpg'),

  ('laura_jones', 'laura.jones@example.com', true, 'password', 'Laura Jones is dedicated to the mission of a charity that focuses on environmental conservation. She is passionate about sustainability and works towards raising awareness about the importance of protecting our planet.', 'Greenfield', 'EcoProvince', 'SavEarth', 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704990010/LHL%20Final%20Project/Users/user-6.jpg'),

  ('ryan_clark', 'ryan.clark@example.com', false, 'password', 'Ryan Clark is a software developer who loves building cutting-edge applications. He stays updated with the latest industry trends and is always eager to explore new technologies to enhance his development skills.', 'Codeville', 'DevLand', 'TechNation', 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704990008/LHL%20Final%20Project/Users/user-7.jpg'),

  ('olivia_morris', 'olivia.morris@example.com', true, 'password', 'Olivia Morris is actively involved in a charity organization that focuses on education for underprivileged children. She believes in the transformative power of education and works towards providing better opportunities for the younger generation.', 'Learnville', 'EduProvince', 'HelpNation', 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704990008/LHL%20Final%20Project/Users/user-8.jpg'),

  ('michael_nguyen', 'michael.nguyen@example.com', false, 'password', 'Michael Nguyen is a software developer with a strong interest in artificial intelligence and machine learning. He enjoys exploring new algorithms and methodologies to create intelligent and efficient software solutions.', 'AICity', 'TechState', 'CodeLand', 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704990010/LHL%20Final%20Project/Users/user-9.jpg'),

  ('grace_baker', 'grace.baker@example.com', true, 'password', 'Grace Baker is dedicated to a charity that focuses on healthcare for disadvantaged communities. She works towards ensuring access to essential medical services and promoting overall well-being in underserved areas.', 'Healthburg', 'MedProvince', 'HelpHealth', 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704990006/LHL%20Final%20Project/Users/user-10.jpg');