INSERT INTO organizations (name, description, website, user_id, image) VALUES
  ('Paws and Claws Foundation', 'Paws and Claws Foundation is committed to the welfare and protection of animals. Our mission is to rescue and care for abused or abandoned animals, advocate for animal rights, and promote responsible pet ownership. Together, let''s create a world where every paw finds a loving home.', 'http://www.pawsandclaws.org', 2, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1705357818/LHL%20Final%20Project/Organizations/org-1_1.webp'),
  
  ('Tiny Miracles Initiative', 'Tiny Miracles Initiative focuses on infant health and well-being. We are dedicated to providing essential healthcare services to newborns, supporting mothers during pregnancy, and ensuring a healthy start for every baby. Join us in nurturing the tiniest miracles of life.', 'http://www.tinymiracles.org', 2, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1705357831/LHL%20Final%20Project/Organizations/org-2_1.webp'),
  
  ('EmpowerHer Alliance', 'EmpowerHer Alliance is a movement dedicated to advancing women''s rights and gender equality. Our initiatives include providing education, training, and support to women, empowering them to achieve their full potential in every aspect of life. Join us in building a world where every woman is empowered and celebrated.', 'http://www.empowerheralliance.org', 4, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1705357832/LHL%20Final%20Project/Organizations/org-3_1.webp'),

  ('HealthHarbor Foundation', 'HealthHarbor Foundation is committed to advancing medical research to improve infant and child health outcomes. Through our funding and collaboration with researchers, we strive to ensure a healthier future for the youngest members of our community.', 'http://www.healthharbor.org', 4, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1705357833/LHL%20Final%20Project/Organizations/org-4_1.webp'),
  
  ('GreenSprout Initiative', 'GreenSprout Initiative is dedicated to environmental conservation and sustainable practices. Join us in protecting and preserving natural habitats, promoting eco-friendly initiatives, and raising awareness about the importance of a balanced ecosystem.', 'http://www.greensprout.org', 6, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1705357834/LHL%20Final%20Project/Organizations/org-5_1.webp'),
  
  ('SafeHaven Network', 'SafeHaven Network focuses on providing shelter, support, and resources to individuals facing homelessness. Join us in our mission to create a community where everyone has a place to call home and the support they need to rebuild their lives.', 'http://www.safehavennetwork.org', 6, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1705357835/LHL%20Final%20Project/Organizations/org-6_1.webp'),

  ('ArtsUplift Foundation', 'ArtsUplift Foundation is dedicated to promoting arts and culture in communities. We support artists, organize cultural events, and provide opportunities for creative expression, fostering a vibrant and diverse cultural landscape. Join us in uplifting communities through the power of art.', 'http://www.artsuplift.org', 10, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1705357837/LHL%20Final%20Project/Organizations/org-7_1.webp'),

  ('AquaHope Initiative', 'AquaHope Initiative works towards providing clean water and sanitation facilities to communities in need. Our projects aim to improve access to safe drinking water, reduce waterborne diseases, and enhance overall hygiene. Join us in bringing hope through clean water.', 'http://www.aquahope.org', 8, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1705357838/LHL%20Final%20Project/Organizations/org-8_1.webp'),

  ('RebuildRise Foundation', 'RebuildRise Foundation is dedicated to disaster relief and humanitarian aid. We respond quickly to natural disasters, providing emergency assistance, rebuilding communities, and helping affected individuals recover and rebuild their lives. Join us in the journey to rebuild and rise together.', 'http://www.rebuildrise.org', 8, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1705357839/LHL%20Final%20Project/Organizations/org-9_1.webp'),

  ('MicroMomentum Foundation', 'MicroMomentum Foundation focuses on tackling poverty through sustainable development projects. Our initiatives include microfinance programs, vocational training, and community empowerment to break the cycle of poverty. Join us in creating positive momentum for lasting change.', 'http://www.micromomentum.org', 10, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1705357840/LHL%20Final%20Project/Organizations/org-10_1.webp');