INSERT INTO projects (name, description, status, organization_id, image) VALUES
('Pet Adoption Platform', 'An online platform for promoting pet adoption, connecting potential adopters with shelters and rescue organizations. The platform includes features such as detailed pet profiles, virtual meet-and-greets, and adoption event notifications to facilitate loving homes for animals in need.', 0, 1, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704992970/LHL%20Final%20Project/Projects/proj-1.jpg'),

('Wildlife Conservation App', 'A mobile application focused on wildlife conservation, providing users with information about endangered species, conservation initiatives, and ways to contribute to the protection of wildlife habitats. The app includes features like virtual tours, educational resources, and opportunities for users to support conservation projects.', 0, 1, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704993071/LHL%20Final%20Project/Projects/proj-2.jpg'),

('Natal Care App', 'A mobile application designed to support new parents and caregivers during pregnancy and the early stages of infancy. The app provides information on prenatal care, baby development milestones, and connects users with healthcare professionals for virtual consultations.', 0, 2, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704992920/LHL%20Final%20Project/Projects/proj-3.jpg'),

('Infant Nutrition Program', 'An initiative focusing on promoting proper nutrition for infants in underserved communities. This project includes the distribution of nutritional supplements, educational materials for caregivers, and organizing workshops on infant feeding practices to ensure the healthy development of infants.', 0, 2, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704992909/LHL%20Final%20Project/Projects/proj-4.jpg'),

('Career Heritage Program', 'An initiative aimed at empowering women by providing mentorship, training, and resources to support their career advancement. The program focuses on breaking gender barriers and promoting equal opportunities in the workplace.', 0, 3, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704993012/LHL%20Final%20Project/Projects/proj-5.jpg'),

('Tech Skills Workshop', 'A series of technology workshops designed to equip women with valuable skills in areas such as coding, digital literacy, and IT. The project aims to bridge the gender gap in the tech industry and empower women to pursue careers in technology.', 0, 3, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704993023/LHL%20Final%20Project/Projects/proj-6.jpg'),

('Community Health Clinic', 'Establishment of a community health clinic to provide accessible and affordable healthcare services to underserved populations. The project includes setting up medical facilities, organizing health education programs, and offering preventive care to improve the overall health of the community.', 0, 4, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704992946/LHL%20Final%20Project/Projects/proj-7.jpg'),

('Green Energy Initiative', 'An environmental initiative focused on promoting green energy solutions and reducing carbon footprint. The project includes implementing solar energy systems, conducting awareness campaigns, and advocating for sustainable energy practices in the community.', 0, 5, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704992931/LHL%20Final%20Project/Projects/proj-8.jpg'),

('Shelter Expansion Project', 'An initiative to expand and improve homeless shelters in the community, providing safe and supportive environments for individuals experiencing homelessness. The project includes renovating existing shelters, increasing capacity, and collaborating with local services to offer comprehensive support for those in need.', 0, 6, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704993061/LHL%20Final%20Project/Projects/proj-9.jpg'),

('Community Mural Project', 'An arts initiative to create vibrant community murals that reflect the cultural diversity and creativity of the neighborhood. The project involves collaborating with local artists, engaging community members in mural design, and hosting public art events to promote community cohesion.', 0, 7, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704993080/LHL%20Final%20Project/Projects/proj-10.jpg'),

('Clean Water Initiative', 'An advocacy project focused on ensuring access to clean and safe water for communities in need. The initiative includes water quality testing, infrastructure improvements, and educational campaigns to promote water conservation and hygiene practices.', 0, 8, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704993000/LHL%20Final%20Project/Projects/proj-11.jpg'),

('Emergency Response Network', 'A disaster relief project aimed at establishing a rapid emergency response network. The project includes training volunteers, creating emergency kits, and developing communication systems to provide timely assistance and support to communities affected by natural disasters.', 0, 9, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704993070/LHL%20Final%20Project/Projects/proj-12.jpg'),

('Empowerment Through Education', 'A poverty relief initiative focused on empowering individuals through education and skill development. The project includes establishing learning centers, providing vocational training, and offering educational resources to break the cycle of poverty and enhance economic opportunities.', 0, 10, 'https://res.cloudinary.com/dphmoqr9f/image/upload/v1704993063/LHL%20Final%20Project/Projects/proj-13.jpg');