INSERT INTO applications (user_id, project_id, text, status) VALUES
(1, 1, 'As a dedicated software developer, I am fueled by a strong passion for creating positive social change. Working on a non-profit project aligns with my values, allowing me to channel my technical skills into building solutions that address real-world issues and make a tangible impact in communities.', 0),
(5, 2, 'I believe in the power of technology to transform lives, and contributing my expertise to a non-profit project is an opportunity to make a meaningful difference. By collaborating on a project that serves a noble cause, I can leverage my coding skills to create solutions that empower and uplift others.', 0),
(5, 3, 'Engaging in a non-profit project provides a unique learning environment where I can enhance my technical abilities while also gaining exposure to diverse problem-solving scenarios. The collaborative nature of such projects allows me to learn from experienced team members and broaden my skill set.', 0),
(3, 4, 'I am drawn to the idea of being part of a purpose-driven community where like-minded individuals come together to contribute their skills for the greater good. Working on a non-profit project creates a collaborative and supportive environment that fosters personal and professional growth.', 0),
(7, 5, 'A non-profit project offers a chance to broaden my perspectives by addressing challenges beyond the scope of traditional software development. This experience will not only enhance my problem-solving skills but also deepen my understanding of the diverse needs within our global society.', 0),
(9, 13, 'Unlike commercial projects, contributing to a non-profit initiative provides the opportunity to create solutions that have a lasting impact on the lives of individuals and communities. This long-term positive effect is a compelling reason for me to invest my time and skills in such projects.', 0),
(7, 12, 'Working on a non-profit project often involves contributing to open-source technologies, fostering collaboration and knowledge-sharing. This aligns with my belief in the principles of open source and the idea that technology should be accessible and beneficial to all.', 0),
(9, 6, 'I view volunteering for a non-profit project as a way to fulfill my social responsibility as a technologist. By utilizing my skills to address societal challenges, I contribute to the greater good and use my expertise for purposes beyond mere profit.', 0),
(1, 6, 'Contributing to a non-profit project allows me to build a portfolio of work that reflects not just my technical proficiency but also my commitment to social responsibility. This dual-purpose approach adds depth and significance to my professional achievements.', 0),
(3, 5, 'Volunteering my time and skills for a non-profit project is a way for me to actively contribute to building a better future. I am eager to be part of a team that leverages technology to address challenges, enhance efficiency, and ultimately improve the lives of those who benefit from your mission.', 0);